### ISSUE TITLE
review height test

### ISSUE THREAD

**Issue by shaunc** [shaunc/ember-grid#15]
@BryanCrotaz -- how did your talk go?

I've pushed some tests: for "height" parameter for the moment. (& a few unit tests)

* Please take a look and tell me if you think this is what we need.
* tests pass on chrome / mac. However, phantomjs tests are failing, and I'm not sure why.

Eg

```
not ok 69 PhantomJS 1.9 - Unit | Utility | potential dimensions: potential dimensions: outer corresponding to parent; inner minus boundary
    ---
        actual: >
            null
        message: >
            Died on test #1     at http://localhost:7357/assets/test-support.js:3062
                at test (http://localhost:7357/assets/test-support.js:1945)
                at test (http://localhost:7357/assets/dummy.js:2090)
                at http://localhost:7357/assets/dummy.js:2908
                at http://localhost:7357/assets/vendor.js:150
                at tryFinally (http://localhost:7357/assets/vendor.js:30)
                at http://localhost:7357/assets/vendor.js:156
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:6775: Can't find variable: Symbol
```

Any ideas?

**Comment by shaunc** [comment]
@BryanCrotaz -- the above error is fixed by 

    babel: {
      includePolyfill: true
    }

This is required by phantomjs and safari. However, phantomjs also has problems with `requestAnimationFrame` which is used in `ember-collection`. :( ... I tried a polyfill but couldn't get it to work. I also tried using firefox in travis, but also couldn't get this to work. If you have experience with travis config (and/or have a way to get phantomjs working) I would be grateful if you give it a shot. I'm going on to "width" tests.

**Comment by BryanCrotaz** [comment]
Not a clue I'm afraid. I'm away doing the lighting for a mini festival until Monday. Have fun till then :)

**Comment by shaunc** [comment]
Have fun yourself! :) ember-collection is tested using circle-ci... for the moment I'll write tests that work in the firefox/chrome/safari on the mac; we can discuss how to go forward when you are back.

Perhaps someone will work on getting ember-collection support -- https://github.com/emberjs/ember-collection/issues/43 ... or perhaps we'll be ready to move on by then.

**Comment by BryanCrotaz** [comment]
not seeing any speed difference with the new code, and column widths still broken on startup in minimal demo.

**Comment by shaunc** [comment]
I'm not very much at least. Pre-rendering 30 extra rows instead of 60 as that isn't problem on scrolling anyway.

I'm still not seeing the columns broken on minimal, but just now I wrote a test that is failing on that same problem -- so hopefully is the same issue (and I'll fix it :))
